name: sandbox
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  evolum_package:
    git:
      url: https://github.com/EvolumOU/evolum_package
  flutter:
    sdk: flutter
  just_audio: ^0.9.20
  just_audio_background: ^0.0.1-beta.5

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
